// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/tuihub/librarian/internal/data/orm/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newNotifyFlowTarget(db *gorm.DB, opts ...gen.DOOption) notifyFlowTarget {
	_notifyFlowTarget := notifyFlowTarget{}

	_notifyFlowTarget.notifyFlowTargetDo.UseDB(db, opts...)
	_notifyFlowTarget.notifyFlowTargetDo.UseModel(&model.NotifyFlowTarget{})

	tableName := _notifyFlowTarget.notifyFlowTargetDo.TableName()
	_notifyFlowTarget.ALL = field.NewAsterisk(tableName)
	_notifyFlowTarget.NotifyFlowID = field.NewInt64(tableName, "notify_flow_id")
	_notifyFlowTarget.NotifyTargetID = field.NewInt64(tableName, "notify_target_id")
	_notifyFlowTarget.FilterIncludeKeywords = field.NewField(tableName, "filter_include_keywords")
	_notifyFlowTarget.FilterExcludeKeywords = field.NewField(tableName, "filter_exclude_keywords")
	_notifyFlowTarget.UpdatedAt = field.NewTime(tableName, "updated_at")
	_notifyFlowTarget.CreatedAt = field.NewTime(tableName, "created_at")

	_notifyFlowTarget.fillFieldMap()

	return _notifyFlowTarget
}

type notifyFlowTarget struct {
	notifyFlowTargetDo notifyFlowTargetDo

	ALL                   field.Asterisk
	NotifyFlowID          field.Int64
	NotifyTargetID        field.Int64
	FilterIncludeKeywords field.Field
	FilterExcludeKeywords field.Field
	UpdatedAt             field.Time
	CreatedAt             field.Time

	fieldMap map[string]field.Expr
}

func (n notifyFlowTarget) Table(newTableName string) *notifyFlowTarget {
	n.notifyFlowTargetDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n notifyFlowTarget) As(alias string) *notifyFlowTarget {
	n.notifyFlowTargetDo.DO = *(n.notifyFlowTargetDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *notifyFlowTarget) updateTableName(table string) *notifyFlowTarget {
	n.ALL = field.NewAsterisk(table)
	n.NotifyFlowID = field.NewInt64(table, "notify_flow_id")
	n.NotifyTargetID = field.NewInt64(table, "notify_target_id")
	n.FilterIncludeKeywords = field.NewField(table, "filter_include_keywords")
	n.FilterExcludeKeywords = field.NewField(table, "filter_exclude_keywords")
	n.UpdatedAt = field.NewTime(table, "updated_at")
	n.CreatedAt = field.NewTime(table, "created_at")

	n.fillFieldMap()

	return n
}

func (n *notifyFlowTarget) WithContext(ctx context.Context) INotifyFlowTargetDo {
	return n.notifyFlowTargetDo.WithContext(ctx)
}

func (n notifyFlowTarget) TableName() string { return n.notifyFlowTargetDo.TableName() }

func (n notifyFlowTarget) Alias() string { return n.notifyFlowTargetDo.Alias() }

func (n notifyFlowTarget) Columns(cols ...field.Expr) gen.Columns {
	return n.notifyFlowTargetDo.Columns(cols...)
}

func (n *notifyFlowTarget) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *notifyFlowTarget) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 6)
	n.fieldMap["notify_flow_id"] = n.NotifyFlowID
	n.fieldMap["notify_target_id"] = n.NotifyTargetID
	n.fieldMap["filter_include_keywords"] = n.FilterIncludeKeywords
	n.fieldMap["filter_exclude_keywords"] = n.FilterExcludeKeywords
	n.fieldMap["updated_at"] = n.UpdatedAt
	n.fieldMap["created_at"] = n.CreatedAt
}

func (n notifyFlowTarget) clone(db *gorm.DB) notifyFlowTarget {
	n.notifyFlowTargetDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n notifyFlowTarget) replaceDB(db *gorm.DB) notifyFlowTarget {
	n.notifyFlowTargetDo.ReplaceDB(db)
	return n
}

type notifyFlowTargetDo struct{ gen.DO }

type INotifyFlowTargetDo interface {
	gen.SubQuery
	Debug() INotifyFlowTargetDo
	WithContext(ctx context.Context) INotifyFlowTargetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INotifyFlowTargetDo
	WriteDB() INotifyFlowTargetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INotifyFlowTargetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INotifyFlowTargetDo
	Not(conds ...gen.Condition) INotifyFlowTargetDo
	Or(conds ...gen.Condition) INotifyFlowTargetDo
	Select(conds ...field.Expr) INotifyFlowTargetDo
	Where(conds ...gen.Condition) INotifyFlowTargetDo
	Order(conds ...field.Expr) INotifyFlowTargetDo
	Distinct(cols ...field.Expr) INotifyFlowTargetDo
	Omit(cols ...field.Expr) INotifyFlowTargetDo
	Join(table schema.Tabler, on ...field.Expr) INotifyFlowTargetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INotifyFlowTargetDo
	RightJoin(table schema.Tabler, on ...field.Expr) INotifyFlowTargetDo
	Group(cols ...field.Expr) INotifyFlowTargetDo
	Having(conds ...gen.Condition) INotifyFlowTargetDo
	Limit(limit int) INotifyFlowTargetDo
	Offset(offset int) INotifyFlowTargetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INotifyFlowTargetDo
	Unscoped() INotifyFlowTargetDo
	Create(values ...*model.NotifyFlowTarget) error
	CreateInBatches(values []*model.NotifyFlowTarget, batchSize int) error
	Save(values ...*model.NotifyFlowTarget) error
	First() (*model.NotifyFlowTarget, error)
	Take() (*model.NotifyFlowTarget, error)
	Last() (*model.NotifyFlowTarget, error)
	Find() ([]*model.NotifyFlowTarget, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotifyFlowTarget, err error)
	FindInBatches(result *[]*model.NotifyFlowTarget, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NotifyFlowTarget) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INotifyFlowTargetDo
	Assign(attrs ...field.AssignExpr) INotifyFlowTargetDo
	Joins(fields ...field.RelationField) INotifyFlowTargetDo
	Preload(fields ...field.RelationField) INotifyFlowTargetDo
	FirstOrInit() (*model.NotifyFlowTarget, error)
	FirstOrCreate() (*model.NotifyFlowTarget, error)
	FindByPage(offset int, limit int) (result []*model.NotifyFlowTarget, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INotifyFlowTargetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n notifyFlowTargetDo) Debug() INotifyFlowTargetDo {
	return n.withDO(n.DO.Debug())
}

func (n notifyFlowTargetDo) WithContext(ctx context.Context) INotifyFlowTargetDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n notifyFlowTargetDo) ReadDB() INotifyFlowTargetDo {
	return n.Clauses(dbresolver.Read)
}

func (n notifyFlowTargetDo) WriteDB() INotifyFlowTargetDo {
	return n.Clauses(dbresolver.Write)
}

func (n notifyFlowTargetDo) Session(config *gorm.Session) INotifyFlowTargetDo {
	return n.withDO(n.DO.Session(config))
}

func (n notifyFlowTargetDo) Clauses(conds ...clause.Expression) INotifyFlowTargetDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n notifyFlowTargetDo) Returning(value interface{}, columns ...string) INotifyFlowTargetDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n notifyFlowTargetDo) Not(conds ...gen.Condition) INotifyFlowTargetDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n notifyFlowTargetDo) Or(conds ...gen.Condition) INotifyFlowTargetDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n notifyFlowTargetDo) Select(conds ...field.Expr) INotifyFlowTargetDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n notifyFlowTargetDo) Where(conds ...gen.Condition) INotifyFlowTargetDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n notifyFlowTargetDo) Order(conds ...field.Expr) INotifyFlowTargetDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n notifyFlowTargetDo) Distinct(cols ...field.Expr) INotifyFlowTargetDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n notifyFlowTargetDo) Omit(cols ...field.Expr) INotifyFlowTargetDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n notifyFlowTargetDo) Join(table schema.Tabler, on ...field.Expr) INotifyFlowTargetDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n notifyFlowTargetDo) LeftJoin(table schema.Tabler, on ...field.Expr) INotifyFlowTargetDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n notifyFlowTargetDo) RightJoin(table schema.Tabler, on ...field.Expr) INotifyFlowTargetDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n notifyFlowTargetDo) Group(cols ...field.Expr) INotifyFlowTargetDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n notifyFlowTargetDo) Having(conds ...gen.Condition) INotifyFlowTargetDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n notifyFlowTargetDo) Limit(limit int) INotifyFlowTargetDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n notifyFlowTargetDo) Offset(offset int) INotifyFlowTargetDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n notifyFlowTargetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INotifyFlowTargetDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n notifyFlowTargetDo) Unscoped() INotifyFlowTargetDo {
	return n.withDO(n.DO.Unscoped())
}

func (n notifyFlowTargetDo) Create(values ...*model.NotifyFlowTarget) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n notifyFlowTargetDo) CreateInBatches(values []*model.NotifyFlowTarget, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n notifyFlowTargetDo) Save(values ...*model.NotifyFlowTarget) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n notifyFlowTargetDo) First() (*model.NotifyFlowTarget, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotifyFlowTarget), nil
	}
}

func (n notifyFlowTargetDo) Take() (*model.NotifyFlowTarget, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotifyFlowTarget), nil
	}
}

func (n notifyFlowTargetDo) Last() (*model.NotifyFlowTarget, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotifyFlowTarget), nil
	}
}

func (n notifyFlowTargetDo) Find() ([]*model.NotifyFlowTarget, error) {
	result, err := n.DO.Find()
	return result.([]*model.NotifyFlowTarget), err
}

func (n notifyFlowTargetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotifyFlowTarget, err error) {
	buf := make([]*model.NotifyFlowTarget, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n notifyFlowTargetDo) FindInBatches(result *[]*model.NotifyFlowTarget, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n notifyFlowTargetDo) Attrs(attrs ...field.AssignExpr) INotifyFlowTargetDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n notifyFlowTargetDo) Assign(attrs ...field.AssignExpr) INotifyFlowTargetDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n notifyFlowTargetDo) Joins(fields ...field.RelationField) INotifyFlowTargetDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n notifyFlowTargetDo) Preload(fields ...field.RelationField) INotifyFlowTargetDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n notifyFlowTargetDo) FirstOrInit() (*model.NotifyFlowTarget, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotifyFlowTarget), nil
	}
}

func (n notifyFlowTargetDo) FirstOrCreate() (*model.NotifyFlowTarget, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotifyFlowTarget), nil
	}
}

func (n notifyFlowTargetDo) FindByPage(offset int, limit int) (result []*model.NotifyFlowTarget, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n notifyFlowTargetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n notifyFlowTargetDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n notifyFlowTargetDo) Delete(models ...*model.NotifyFlowTarget) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *notifyFlowTargetDo) withDO(do gen.Dao) *notifyFlowTargetDo {
	n.DO = *do.(*gen.DO)
	return n
}
