// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/tuihub/librarian/internal/data/orm/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSentinel(db *gorm.DB, opts ...gen.DOOption) sentinel {
	_sentinel := sentinel{}

	_sentinel.sentinelDo.UseDB(db, opts...)
	_sentinel.sentinelDo.UseModel(&model.Sentinel{})

	tableName := _sentinel.sentinelDo.TableName()
	_sentinel.ALL = field.NewAsterisk(tableName)
	_sentinel.ID = field.NewInt64(tableName, "id")
	_sentinel.Name = field.NewString(tableName, "name")
	_sentinel.Description = field.NewString(tableName, "description")
	_sentinel.URL = field.NewString(tableName, "url")
	_sentinel.AlternativeURLs = field.NewField(tableName, "alternative_urls")
	_sentinel.GetTokenPath = field.NewString(tableName, "get_token_path")
	_sentinel.DownloadFileBasePath = field.NewString(tableName, "download_file_base_path")
	_sentinel.CreatorID = field.NewInt64(tableName, "creator_id")
	_sentinel.LibraryReportSequence = field.NewInt64(tableName, "library_report_sequence")
	_sentinel.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sentinel.CreatedAt = field.NewTime(tableName, "created_at")
	_sentinel.SentinelSessions = sentinelHasManySentinelSessions{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SentinelSessions", "model.SentinelSession"),
		Sentinel: struct {
			field.RelationField
			SentinelSessions struct {
				field.RelationField
			}
			SentinelLibraries struct {
				field.RelationField
				Sentinel struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("SentinelSessions.Sentinel", "model.Sentinel"),
			SentinelSessions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("SentinelSessions.Sentinel.SentinelSessions", "model.SentinelSession"),
			},
			SentinelLibraries: struct {
				field.RelationField
				Sentinel struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("SentinelSessions.Sentinel.SentinelLibraries", "model.SentinelLibrary"),
				Sentinel: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("SentinelSessions.Sentinel.SentinelLibraries.Sentinel", "model.Sentinel"),
				},
			},
		},
	}

	_sentinel.SentinelLibraries = sentinelHasManySentinelLibraries{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SentinelLibraries", "model.SentinelLibrary"),
	}

	_sentinel.fillFieldMap()

	return _sentinel
}

type sentinel struct {
	sentinelDo sentinelDo

	ALL                   field.Asterisk
	ID                    field.Int64
	Name                  field.String
	Description           field.String
	URL                   field.String
	AlternativeURLs       field.Field
	GetTokenPath          field.String
	DownloadFileBasePath  field.String
	CreatorID             field.Int64
	LibraryReportSequence field.Int64
	UpdatedAt             field.Time
	CreatedAt             field.Time
	SentinelSessions      sentinelHasManySentinelSessions

	SentinelLibraries sentinelHasManySentinelLibraries

	fieldMap map[string]field.Expr
}

func (s sentinel) Table(newTableName string) *sentinel {
	s.sentinelDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sentinel) As(alias string) *sentinel {
	s.sentinelDo.DO = *(s.sentinelDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sentinel) updateTableName(table string) *sentinel {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.Description = field.NewString(table, "description")
	s.URL = field.NewString(table, "url")
	s.AlternativeURLs = field.NewField(table, "alternative_urls")
	s.GetTokenPath = field.NewString(table, "get_token_path")
	s.DownloadFileBasePath = field.NewString(table, "download_file_base_path")
	s.CreatorID = field.NewInt64(table, "creator_id")
	s.LibraryReportSequence = field.NewInt64(table, "library_report_sequence")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *sentinel) WithContext(ctx context.Context) ISentinelDo { return s.sentinelDo.WithContext(ctx) }

func (s sentinel) TableName() string { return s.sentinelDo.TableName() }

func (s sentinel) Alias() string { return s.sentinelDo.Alias() }

func (s sentinel) Columns(cols ...field.Expr) gen.Columns { return s.sentinelDo.Columns(cols...) }

func (s *sentinel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sentinel) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 13)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["description"] = s.Description
	s.fieldMap["url"] = s.URL
	s.fieldMap["alternative_urls"] = s.AlternativeURLs
	s.fieldMap["get_token_path"] = s.GetTokenPath
	s.fieldMap["download_file_base_path"] = s.DownloadFileBasePath
	s.fieldMap["creator_id"] = s.CreatorID
	s.fieldMap["library_report_sequence"] = s.LibraryReportSequence
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["created_at"] = s.CreatedAt

}

func (s sentinel) clone(db *gorm.DB) sentinel {
	s.sentinelDo.ReplaceConnPool(db.Statement.ConnPool)
	s.SentinelSessions.db = db.Session(&gorm.Session{Initialized: true})
	s.SentinelSessions.db.Statement.ConnPool = db.Statement.ConnPool
	s.SentinelLibraries.db = db.Session(&gorm.Session{Initialized: true})
	s.SentinelLibraries.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sentinel) replaceDB(db *gorm.DB) sentinel {
	s.sentinelDo.ReplaceDB(db)
	s.SentinelSessions.db = db.Session(&gorm.Session{})
	s.SentinelLibraries.db = db.Session(&gorm.Session{})
	return s
}

type sentinelHasManySentinelSessions struct {
	db *gorm.DB

	field.RelationField

	Sentinel struct {
		field.RelationField
		SentinelSessions struct {
			field.RelationField
		}
		SentinelLibraries struct {
			field.RelationField
			Sentinel struct {
				field.RelationField
			}
		}
	}
}

func (a sentinelHasManySentinelSessions) Where(conds ...field.Expr) *sentinelHasManySentinelSessions {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sentinelHasManySentinelSessions) WithContext(ctx context.Context) *sentinelHasManySentinelSessions {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sentinelHasManySentinelSessions) Session(session *gorm.Session) *sentinelHasManySentinelSessions {
	a.db = a.db.Session(session)
	return &a
}

func (a sentinelHasManySentinelSessions) Model(m *model.Sentinel) *sentinelHasManySentinelSessionsTx {
	return &sentinelHasManySentinelSessionsTx{a.db.Model(m).Association(a.Name())}
}

func (a sentinelHasManySentinelSessions) Unscoped() *sentinelHasManySentinelSessions {
	a.db = a.db.Unscoped()
	return &a
}

type sentinelHasManySentinelSessionsTx struct{ tx *gorm.Association }

func (a sentinelHasManySentinelSessionsTx) Find() (result []*model.SentinelSession, err error) {
	return result, a.tx.Find(&result)
}

func (a sentinelHasManySentinelSessionsTx) Append(values ...*model.SentinelSession) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sentinelHasManySentinelSessionsTx) Replace(values ...*model.SentinelSession) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sentinelHasManySentinelSessionsTx) Delete(values ...*model.SentinelSession) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sentinelHasManySentinelSessionsTx) Clear() error {
	return a.tx.Clear()
}

func (a sentinelHasManySentinelSessionsTx) Count() int64 {
	return a.tx.Count()
}

func (a sentinelHasManySentinelSessionsTx) Unscoped() *sentinelHasManySentinelSessionsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sentinelHasManySentinelLibraries struct {
	db *gorm.DB

	field.RelationField
}

func (a sentinelHasManySentinelLibraries) Where(conds ...field.Expr) *sentinelHasManySentinelLibraries {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sentinelHasManySentinelLibraries) WithContext(ctx context.Context) *sentinelHasManySentinelLibraries {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sentinelHasManySentinelLibraries) Session(session *gorm.Session) *sentinelHasManySentinelLibraries {
	a.db = a.db.Session(session)
	return &a
}

func (a sentinelHasManySentinelLibraries) Model(m *model.Sentinel) *sentinelHasManySentinelLibrariesTx {
	return &sentinelHasManySentinelLibrariesTx{a.db.Model(m).Association(a.Name())}
}

func (a sentinelHasManySentinelLibraries) Unscoped() *sentinelHasManySentinelLibraries {
	a.db = a.db.Unscoped()
	return &a
}

type sentinelHasManySentinelLibrariesTx struct{ tx *gorm.Association }

func (a sentinelHasManySentinelLibrariesTx) Find() (result []*model.SentinelLibrary, err error) {
	return result, a.tx.Find(&result)
}

func (a sentinelHasManySentinelLibrariesTx) Append(values ...*model.SentinelLibrary) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sentinelHasManySentinelLibrariesTx) Replace(values ...*model.SentinelLibrary) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sentinelHasManySentinelLibrariesTx) Delete(values ...*model.SentinelLibrary) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sentinelHasManySentinelLibrariesTx) Clear() error {
	return a.tx.Clear()
}

func (a sentinelHasManySentinelLibrariesTx) Count() int64 {
	return a.tx.Count()
}

func (a sentinelHasManySentinelLibrariesTx) Unscoped() *sentinelHasManySentinelLibrariesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sentinelDo struct{ gen.DO }

type ISentinelDo interface {
	gen.SubQuery
	Debug() ISentinelDo
	WithContext(ctx context.Context) ISentinelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISentinelDo
	WriteDB() ISentinelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISentinelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISentinelDo
	Not(conds ...gen.Condition) ISentinelDo
	Or(conds ...gen.Condition) ISentinelDo
	Select(conds ...field.Expr) ISentinelDo
	Where(conds ...gen.Condition) ISentinelDo
	Order(conds ...field.Expr) ISentinelDo
	Distinct(cols ...field.Expr) ISentinelDo
	Omit(cols ...field.Expr) ISentinelDo
	Join(table schema.Tabler, on ...field.Expr) ISentinelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISentinelDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISentinelDo
	Group(cols ...field.Expr) ISentinelDo
	Having(conds ...gen.Condition) ISentinelDo
	Limit(limit int) ISentinelDo
	Offset(offset int) ISentinelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISentinelDo
	Unscoped() ISentinelDo
	Create(values ...*model.Sentinel) error
	CreateInBatches(values []*model.Sentinel, batchSize int) error
	Save(values ...*model.Sentinel) error
	First() (*model.Sentinel, error)
	Take() (*model.Sentinel, error)
	Last() (*model.Sentinel, error)
	Find() ([]*model.Sentinel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Sentinel, err error)
	FindInBatches(result *[]*model.Sentinel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Sentinel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISentinelDo
	Assign(attrs ...field.AssignExpr) ISentinelDo
	Joins(fields ...field.RelationField) ISentinelDo
	Preload(fields ...field.RelationField) ISentinelDo
	FirstOrInit() (*model.Sentinel, error)
	FirstOrCreate() (*model.Sentinel, error)
	FindByPage(offset int, limit int) (result []*model.Sentinel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISentinelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sentinelDo) Debug() ISentinelDo {
	return s.withDO(s.DO.Debug())
}

func (s sentinelDo) WithContext(ctx context.Context) ISentinelDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sentinelDo) ReadDB() ISentinelDo {
	return s.Clauses(dbresolver.Read)
}

func (s sentinelDo) WriteDB() ISentinelDo {
	return s.Clauses(dbresolver.Write)
}

func (s sentinelDo) Session(config *gorm.Session) ISentinelDo {
	return s.withDO(s.DO.Session(config))
}

func (s sentinelDo) Clauses(conds ...clause.Expression) ISentinelDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sentinelDo) Returning(value interface{}, columns ...string) ISentinelDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sentinelDo) Not(conds ...gen.Condition) ISentinelDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sentinelDo) Or(conds ...gen.Condition) ISentinelDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sentinelDo) Select(conds ...field.Expr) ISentinelDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sentinelDo) Where(conds ...gen.Condition) ISentinelDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sentinelDo) Order(conds ...field.Expr) ISentinelDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sentinelDo) Distinct(cols ...field.Expr) ISentinelDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sentinelDo) Omit(cols ...field.Expr) ISentinelDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sentinelDo) Join(table schema.Tabler, on ...field.Expr) ISentinelDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sentinelDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISentinelDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sentinelDo) RightJoin(table schema.Tabler, on ...field.Expr) ISentinelDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sentinelDo) Group(cols ...field.Expr) ISentinelDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sentinelDo) Having(conds ...gen.Condition) ISentinelDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sentinelDo) Limit(limit int) ISentinelDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sentinelDo) Offset(offset int) ISentinelDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sentinelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISentinelDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sentinelDo) Unscoped() ISentinelDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sentinelDo) Create(values ...*model.Sentinel) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sentinelDo) CreateInBatches(values []*model.Sentinel, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sentinelDo) Save(values ...*model.Sentinel) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sentinelDo) First() (*model.Sentinel, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Sentinel), nil
	}
}

func (s sentinelDo) Take() (*model.Sentinel, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Sentinel), nil
	}
}

func (s sentinelDo) Last() (*model.Sentinel, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Sentinel), nil
	}
}

func (s sentinelDo) Find() ([]*model.Sentinel, error) {
	result, err := s.DO.Find()
	return result.([]*model.Sentinel), err
}

func (s sentinelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Sentinel, err error) {
	buf := make([]*model.Sentinel, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sentinelDo) FindInBatches(result *[]*model.Sentinel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sentinelDo) Attrs(attrs ...field.AssignExpr) ISentinelDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sentinelDo) Assign(attrs ...field.AssignExpr) ISentinelDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sentinelDo) Joins(fields ...field.RelationField) ISentinelDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sentinelDo) Preload(fields ...field.RelationField) ISentinelDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sentinelDo) FirstOrInit() (*model.Sentinel, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Sentinel), nil
	}
}

func (s sentinelDo) FirstOrCreate() (*model.Sentinel, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Sentinel), nil
	}
}

func (s sentinelDo) FindByPage(offset int, limit int) (result []*model.Sentinel, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sentinelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sentinelDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sentinelDo) Delete(models ...*model.Sentinel) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sentinelDo) withDO(do gen.Dao) *sentinelDo {
	s.DO = *do.(*gen.DO)
	return s
}
