// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/tuihub/librarian/internal/data/orm/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSession(db *gorm.DB, opts ...gen.DOOption) session {
	_session := session{}

	_session.sessionDo.UseDB(db, opts...)
	_session.sessionDo.UseModel(&model.Session{})

	tableName := _session.sessionDo.TableName()
	_session.ALL = field.NewAsterisk(tableName)
	_session.ID = field.NewInt64(tableName, "id")
	_session.UserID = field.NewInt64(tableName, "user_id")
	_session.DeviceID = field.NewInt64(tableName, "device_id")
	_session.RefreshToken = field.NewString(tableName, "refresh_token")
	_session.ExpireAt = field.NewTime(tableName, "expire_at")
	_session.UpdatedAt = field.NewTime(tableName, "updated_at")
	_session.CreatedAt = field.NewTime(tableName, "created_at")
	_session.User = sessionBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.User"),
		Creator: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.Creator", "model.User"),
		},
		Sessions: struct {
			field.RelationField
			User struct {
				field.RelationField
			}
			Device struct {
				field.RelationField
				Sessions struct {
					field.RelationField
				}
				App struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					Device struct {
						field.RelationField
					}
					AppRunTime struct {
						field.RelationField
						App struct {
							field.RelationField
						}
					}
					AppCategories struct {
						field.RelationField
						AppAppCategories struct {
							field.RelationField
						}
						Apps struct {
							field.RelationField
						}
					}
				}
			}
		}{
			RelationField: field.NewRelation("User.Sessions", "model.Session"),
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Sessions.User", "model.User"),
			},
			Device: struct {
				field.RelationField
				Sessions struct {
					field.RelationField
				}
				App struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					Device struct {
						field.RelationField
					}
					AppRunTime struct {
						field.RelationField
						App struct {
							field.RelationField
						}
					}
					AppCategories struct {
						field.RelationField
						AppAppCategories struct {
							field.RelationField
						}
						Apps struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("User.Sessions.Device", "model.Device"),
				Sessions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Sessions.Device.Sessions", "model.Session"),
				},
				App: struct {
					field.RelationField
					User struct {
						field.RelationField
					}
					Device struct {
						field.RelationField
					}
					AppRunTime struct {
						field.RelationField
						App struct {
							field.RelationField
						}
					}
					AppCategories struct {
						field.RelationField
						AppAppCategories struct {
							field.RelationField
						}
						Apps struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("User.Sessions.Device.App", "model.App"),
					User: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("User.Sessions.Device.App.User", "model.User"),
					},
					Device: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("User.Sessions.Device.App.Device", "model.Device"),
					},
					AppRunTime: struct {
						field.RelationField
						App struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("User.Sessions.Device.App.AppRunTime", "model.AppRunTime"),
						App: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("User.Sessions.Device.App.AppRunTime.App", "model.App"),
						},
					},
					AppCategories: struct {
						field.RelationField
						AppAppCategories struct {
							field.RelationField
						}
						Apps struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("User.Sessions.Device.App.AppCategories", "model.AppCategory"),
						AppAppCategories: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("User.Sessions.Device.App.AppCategories.AppAppCategories", "model.AppAppCategory"),
						},
						Apps: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("User.Sessions.Device.App.AppCategories.Apps", "model.App"),
						},
					},
				},
			},
		},
		Account: struct {
			field.RelationField
			BoundUser struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Account", "model.Account"),
			BoundUser: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Account.BoundUser", "model.User"),
			},
		},
		App: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.App", "model.App"),
		},
		FeedConfig: struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			Feed struct {
				field.RelationField
				Config struct {
					field.RelationField
				}
				Item struct {
					field.RelationField
					Feed struct {
						field.RelationField
					}
					FeedItemCollections struct {
						field.RelationField
						Owner struct {
							field.RelationField
						}
						NotifySource struct {
							field.RelationField
							Owner struct {
								field.RelationField
							}
							FeedConfig struct {
								field.RelationField
							}
							FeedItemCollection struct {
								field.RelationField
							}
							NotifyFlows struct {
								field.RelationField
								Owner struct {
									field.RelationField
								}
								NotifyFlowTargets struct {
									field.RelationField
								}
								NotifyFlowSources struct {
									field.RelationField
								}
								NotifyTargets struct {
									field.RelationField
									Owner struct {
										field.RelationField
									}
									NotifyFlows struct {
										field.RelationField
									}
								}
								NotifySources struct {
									field.RelationField
								}
							}
						}
						FeedItems struct {
							field.RelationField
						}
					}
				}
			}
			NotifySource struct {
				field.RelationField
			}
			FeedActionSets struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				FeedConfigs struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("User.FeedConfig", "model.FeedConfig"),
			Owner: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.FeedConfig.Owner", "model.User"),
			},
			Feed: struct {
				field.RelationField
				Config struct {
					field.RelationField
				}
				Item struct {
					field.RelationField
					Feed struct {
						field.RelationField
					}
					FeedItemCollections struct {
						field.RelationField
						Owner struct {
							field.RelationField
						}
						NotifySource struct {
							field.RelationField
							Owner struct {
								field.RelationField
							}
							FeedConfig struct {
								field.RelationField
							}
							FeedItemCollection struct {
								field.RelationField
							}
							NotifyFlows struct {
								field.RelationField
								Owner struct {
									field.RelationField
								}
								NotifyFlowTargets struct {
									field.RelationField
								}
								NotifyFlowSources struct {
									field.RelationField
								}
								NotifyTargets struct {
									field.RelationField
									Owner struct {
										field.RelationField
									}
									NotifyFlows struct {
										field.RelationField
									}
								}
								NotifySources struct {
									field.RelationField
								}
							}
						}
						FeedItems struct {
							field.RelationField
						}
					}
				}
			}{
				RelationField: field.NewRelation("User.FeedConfig.Feed", "model.Feed"),
				Config: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.FeedConfig.Feed.Config", "model.FeedConfig"),
				},
				Item: struct {
					field.RelationField
					Feed struct {
						field.RelationField
					}
					FeedItemCollections struct {
						field.RelationField
						Owner struct {
							field.RelationField
						}
						NotifySource struct {
							field.RelationField
							Owner struct {
								field.RelationField
							}
							FeedConfig struct {
								field.RelationField
							}
							FeedItemCollection struct {
								field.RelationField
							}
							NotifyFlows struct {
								field.RelationField
								Owner struct {
									field.RelationField
								}
								NotifyFlowTargets struct {
									field.RelationField
								}
								NotifyFlowSources struct {
									field.RelationField
								}
								NotifyTargets struct {
									field.RelationField
									Owner struct {
										field.RelationField
									}
									NotifyFlows struct {
										field.RelationField
									}
								}
								NotifySources struct {
									field.RelationField
								}
							}
						}
						FeedItems struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("User.FeedConfig.Feed.Item", "model.FeedItem"),
					Feed: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("User.FeedConfig.Feed.Item.Feed", "model.Feed"),
					},
					FeedItemCollections: struct {
						field.RelationField
						Owner struct {
							field.RelationField
						}
						NotifySource struct {
							field.RelationField
							Owner struct {
								field.RelationField
							}
							FeedConfig struct {
								field.RelationField
							}
							FeedItemCollection struct {
								field.RelationField
							}
							NotifyFlows struct {
								field.RelationField
								Owner struct {
									field.RelationField
								}
								NotifyFlowTargets struct {
									field.RelationField
								}
								NotifyFlowSources struct {
									field.RelationField
								}
								NotifyTargets struct {
									field.RelationField
									Owner struct {
										field.RelationField
									}
									NotifyFlows struct {
										field.RelationField
									}
								}
								NotifySources struct {
									field.RelationField
								}
							}
						}
						FeedItems struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections", "model.FeedItemCollection"),
						Owner: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.Owner", "model.User"),
						},
						NotifySource: struct {
							field.RelationField
							Owner struct {
								field.RelationField
							}
							FeedConfig struct {
								field.RelationField
							}
							FeedItemCollection struct {
								field.RelationField
							}
							NotifyFlows struct {
								field.RelationField
								Owner struct {
									field.RelationField
								}
								NotifyFlowTargets struct {
									field.RelationField
								}
								NotifyFlowSources struct {
									field.RelationField
								}
								NotifyTargets struct {
									field.RelationField
									Owner struct {
										field.RelationField
									}
									NotifyFlows struct {
										field.RelationField
									}
								}
								NotifySources struct {
									field.RelationField
								}
							}
						}{
							RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.NotifySource", "model.NotifySource"),
							Owner: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.NotifySource.Owner", "model.User"),
							},
							FeedConfig: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.NotifySource.FeedConfig", "model.FeedConfig"),
							},
							FeedItemCollection: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.NotifySource.FeedItemCollection", "model.FeedItemCollection"),
							},
							NotifyFlows: struct {
								field.RelationField
								Owner struct {
									field.RelationField
								}
								NotifyFlowTargets struct {
									field.RelationField
								}
								NotifyFlowSources struct {
									field.RelationField
								}
								NotifyTargets struct {
									field.RelationField
									Owner struct {
										field.RelationField
									}
									NotifyFlows struct {
										field.RelationField
									}
								}
								NotifySources struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.NotifySource.NotifyFlows", "model.NotifyFlow"),
								Owner: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.NotifySource.NotifyFlows.Owner", "model.User"),
								},
								NotifyFlowTargets: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.NotifySource.NotifyFlows.NotifyFlowTargets", "model.NotifyFlowTarget"),
								},
								NotifyFlowSources: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.NotifySource.NotifyFlows.NotifyFlowSources", "model.NotifyFlowSource"),
								},
								NotifyTargets: struct {
									field.RelationField
									Owner struct {
										field.RelationField
									}
									NotifyFlows struct {
										field.RelationField
									}
								}{
									RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.NotifySource.NotifyFlows.NotifyTargets", "model.NotifyTarget"),
									Owner: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.NotifySource.NotifyFlows.NotifyTargets.Owner", "model.User"),
									},
									NotifyFlows: struct {
										field.RelationField
									}{
										RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.NotifySource.NotifyFlows.NotifyTargets.NotifyFlows", "model.NotifyFlow"),
									},
								},
								NotifySources: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.NotifySource.NotifyFlows.NotifySources", "model.NotifySource"),
								},
							},
						},
						FeedItems: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("User.FeedConfig.Feed.Item.FeedItemCollections.FeedItems", "model.FeedItem"),
						},
					},
				},
			},
			NotifySource: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.FeedConfig.NotifySource", "model.NotifySource"),
			},
			FeedActionSets: struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				FeedConfigs struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.FeedConfig.FeedActionSets", "model.FeedActionSet"),
				Owner: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.FeedConfig.FeedActionSets.Owner", "model.User"),
				},
				FeedConfigs: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.FeedConfig.FeedActionSets.FeedConfigs", "model.FeedConfig"),
				},
			},
		},
		NotifySource: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.NotifySource", "model.NotifySource"),
		},
		NotifyTarget: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.NotifyTarget", "model.NotifyTarget"),
		},
		NotifyFlow: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.NotifyFlow", "model.NotifyFlow"),
		},
		Image: struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			File struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Image struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("User.Image", "model.Image"),
			Owner: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Image.Owner", "model.User"),
			},
			File: struct {
				field.RelationField
				Owner struct {
					field.RelationField
				}
				Image struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("User.Image.File", "model.File"),
				Owner: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Image.File.Owner", "model.User"),
				},
				Image: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("User.Image.File.Image", "model.Image"),
				},
			},
		},
		File: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.File", "model.File"),
		},
		Tag: struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.Tag", "model.Tag"),
			Owner: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.Tag.Owner", "model.User"),
			},
		},
		PorterContext: struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("User.PorterContext", "model.PorterContext"),
			Owner: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("User.PorterContext.Owner", "model.User"),
			},
		},
		CreatedUser: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.CreatedUser", "model.User"),
		},
	}

	_session.Device = sessionBelongsToDevice{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Device", "model.Device"),
	}

	_session.fillFieldMap()

	return _session
}

type session struct {
	sessionDo sessionDo

	ALL          field.Asterisk
	ID           field.Int64
	UserID       field.Int64
	DeviceID     field.Int64
	RefreshToken field.String
	ExpireAt     field.Time
	UpdatedAt    field.Time
	CreatedAt    field.Time
	User         sessionBelongsToUser

	Device sessionBelongsToDevice

	fieldMap map[string]field.Expr
}

func (s session) Table(newTableName string) *session {
	s.sessionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s session) As(alias string) *session {
	s.sessionDo.DO = *(s.sessionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *session) updateTableName(table string) *session {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.UserID = field.NewInt64(table, "user_id")
	s.DeviceID = field.NewInt64(table, "device_id")
	s.RefreshToken = field.NewString(table, "refresh_token")
	s.ExpireAt = field.NewTime(table, "expire_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *session) WithContext(ctx context.Context) ISessionDo { return s.sessionDo.WithContext(ctx) }

func (s session) TableName() string { return s.sessionDo.TableName() }

func (s session) Alias() string { return s.sessionDo.Alias() }

func (s session) Columns(cols ...field.Expr) gen.Columns { return s.sessionDo.Columns(cols...) }

func (s *session) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *session) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["device_id"] = s.DeviceID
	s.fieldMap["refresh_token"] = s.RefreshToken
	s.fieldMap["expire_at"] = s.ExpireAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["created_at"] = s.CreatedAt

}

func (s session) clone(db *gorm.DB) session {
	s.sessionDo.ReplaceConnPool(db.Statement.ConnPool)
	s.User.db = db.Session(&gorm.Session{Initialized: true})
	s.User.db.Statement.ConnPool = db.Statement.ConnPool
	s.Device.db = db.Session(&gorm.Session{Initialized: true})
	s.Device.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s session) replaceDB(db *gorm.DB) session {
	s.sessionDo.ReplaceDB(db)
	s.User.db = db.Session(&gorm.Session{})
	s.Device.db = db.Session(&gorm.Session{})
	return s
}

type sessionBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	Creator struct {
		field.RelationField
	}
	Sessions struct {
		field.RelationField
		User struct {
			field.RelationField
		}
		Device struct {
			field.RelationField
			Sessions struct {
				field.RelationField
			}
			App struct {
				field.RelationField
				User struct {
					field.RelationField
				}
				Device struct {
					field.RelationField
				}
				AppRunTime struct {
					field.RelationField
					App struct {
						field.RelationField
					}
				}
				AppCategories struct {
					field.RelationField
					AppAppCategories struct {
						field.RelationField
					}
					Apps struct {
						field.RelationField
					}
				}
			}
		}
	}
	Account struct {
		field.RelationField
		BoundUser struct {
			field.RelationField
		}
	}
	App struct {
		field.RelationField
	}
	FeedConfig struct {
		field.RelationField
		Owner struct {
			field.RelationField
		}
		Feed struct {
			field.RelationField
			Config struct {
				field.RelationField
			}
			Item struct {
				field.RelationField
				Feed struct {
					field.RelationField
				}
				FeedItemCollections struct {
					field.RelationField
					Owner struct {
						field.RelationField
					}
					NotifySource struct {
						field.RelationField
						Owner struct {
							field.RelationField
						}
						FeedConfig struct {
							field.RelationField
						}
						FeedItemCollection struct {
							field.RelationField
						}
						NotifyFlows struct {
							field.RelationField
							Owner struct {
								field.RelationField
							}
							NotifyFlowTargets struct {
								field.RelationField
							}
							NotifyFlowSources struct {
								field.RelationField
							}
							NotifyTargets struct {
								field.RelationField
								Owner struct {
									field.RelationField
								}
								NotifyFlows struct {
									field.RelationField
								}
							}
							NotifySources struct {
								field.RelationField
							}
						}
					}
					FeedItems struct {
						field.RelationField
					}
				}
			}
		}
		NotifySource struct {
			field.RelationField
		}
		FeedActionSets struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			FeedConfigs struct {
				field.RelationField
			}
		}
	}
	NotifySource struct {
		field.RelationField
	}
	NotifyTarget struct {
		field.RelationField
	}
	NotifyFlow struct {
		field.RelationField
	}
	Image struct {
		field.RelationField
		Owner struct {
			field.RelationField
		}
		File struct {
			field.RelationField
			Owner struct {
				field.RelationField
			}
			Image struct {
				field.RelationField
			}
		}
	}
	File struct {
		field.RelationField
	}
	Tag struct {
		field.RelationField
		Owner struct {
			field.RelationField
		}
	}
	PorterContext struct {
		field.RelationField
		Owner struct {
			field.RelationField
		}
	}
	CreatedUser struct {
		field.RelationField
	}
}

func (a sessionBelongsToUser) Where(conds ...field.Expr) *sessionBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sessionBelongsToUser) WithContext(ctx context.Context) *sessionBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sessionBelongsToUser) Session(session *gorm.Session) *sessionBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a sessionBelongsToUser) Model(m *model.Session) *sessionBelongsToUserTx {
	return &sessionBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a sessionBelongsToUser) Unscoped() *sessionBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type sessionBelongsToUserTx struct{ tx *gorm.Association }

func (a sessionBelongsToUserTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a sessionBelongsToUserTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sessionBelongsToUserTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sessionBelongsToUserTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sessionBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a sessionBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a sessionBelongsToUserTx) Unscoped() *sessionBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sessionBelongsToDevice struct {
	db *gorm.DB

	field.RelationField
}

func (a sessionBelongsToDevice) Where(conds ...field.Expr) *sessionBelongsToDevice {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sessionBelongsToDevice) WithContext(ctx context.Context) *sessionBelongsToDevice {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sessionBelongsToDevice) Session(session *gorm.Session) *sessionBelongsToDevice {
	a.db = a.db.Session(session)
	return &a
}

func (a sessionBelongsToDevice) Model(m *model.Session) *sessionBelongsToDeviceTx {
	return &sessionBelongsToDeviceTx{a.db.Model(m).Association(a.Name())}
}

func (a sessionBelongsToDevice) Unscoped() *sessionBelongsToDevice {
	a.db = a.db.Unscoped()
	return &a
}

type sessionBelongsToDeviceTx struct{ tx *gorm.Association }

func (a sessionBelongsToDeviceTx) Find() (result *model.Device, err error) {
	return result, a.tx.Find(&result)
}

func (a sessionBelongsToDeviceTx) Append(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sessionBelongsToDeviceTx) Replace(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sessionBelongsToDeviceTx) Delete(values ...*model.Device) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sessionBelongsToDeviceTx) Clear() error {
	return a.tx.Clear()
}

func (a sessionBelongsToDeviceTx) Count() int64 {
	return a.tx.Count()
}

func (a sessionBelongsToDeviceTx) Unscoped() *sessionBelongsToDeviceTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sessionDo struct{ gen.DO }

type ISessionDo interface {
	gen.SubQuery
	Debug() ISessionDo
	WithContext(ctx context.Context) ISessionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISessionDo
	WriteDB() ISessionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISessionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISessionDo
	Not(conds ...gen.Condition) ISessionDo
	Or(conds ...gen.Condition) ISessionDo
	Select(conds ...field.Expr) ISessionDo
	Where(conds ...gen.Condition) ISessionDo
	Order(conds ...field.Expr) ISessionDo
	Distinct(cols ...field.Expr) ISessionDo
	Omit(cols ...field.Expr) ISessionDo
	Join(table schema.Tabler, on ...field.Expr) ISessionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISessionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISessionDo
	Group(cols ...field.Expr) ISessionDo
	Having(conds ...gen.Condition) ISessionDo
	Limit(limit int) ISessionDo
	Offset(offset int) ISessionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionDo
	Unscoped() ISessionDo
	Create(values ...*model.Session) error
	CreateInBatches(values []*model.Session, batchSize int) error
	Save(values ...*model.Session) error
	First() (*model.Session, error)
	Take() (*model.Session, error)
	Last() (*model.Session, error)
	Find() ([]*model.Session, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Session, err error)
	FindInBatches(result *[]*model.Session, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Session) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISessionDo
	Assign(attrs ...field.AssignExpr) ISessionDo
	Joins(fields ...field.RelationField) ISessionDo
	Preload(fields ...field.RelationField) ISessionDo
	FirstOrInit() (*model.Session, error)
	FirstOrCreate() (*model.Session, error)
	FindByPage(offset int, limit int) (result []*model.Session, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISessionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sessionDo) Debug() ISessionDo {
	return s.withDO(s.DO.Debug())
}

func (s sessionDo) WithContext(ctx context.Context) ISessionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sessionDo) ReadDB() ISessionDo {
	return s.Clauses(dbresolver.Read)
}

func (s sessionDo) WriteDB() ISessionDo {
	return s.Clauses(dbresolver.Write)
}

func (s sessionDo) Session(config *gorm.Session) ISessionDo {
	return s.withDO(s.DO.Session(config))
}

func (s sessionDo) Clauses(conds ...clause.Expression) ISessionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sessionDo) Returning(value interface{}, columns ...string) ISessionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sessionDo) Not(conds ...gen.Condition) ISessionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sessionDo) Or(conds ...gen.Condition) ISessionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sessionDo) Select(conds ...field.Expr) ISessionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sessionDo) Where(conds ...gen.Condition) ISessionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sessionDo) Order(conds ...field.Expr) ISessionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sessionDo) Distinct(cols ...field.Expr) ISessionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sessionDo) Omit(cols ...field.Expr) ISessionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sessionDo) Join(table schema.Tabler, on ...field.Expr) ISessionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISessionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sessionDo) RightJoin(table schema.Tabler, on ...field.Expr) ISessionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sessionDo) Group(cols ...field.Expr) ISessionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sessionDo) Having(conds ...gen.Condition) ISessionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sessionDo) Limit(limit int) ISessionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sessionDo) Offset(offset int) ISessionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISessionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sessionDo) Unscoped() ISessionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sessionDo) Create(values ...*model.Session) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sessionDo) CreateInBatches(values []*model.Session, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sessionDo) Save(values ...*model.Session) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sessionDo) First() (*model.Session, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Session), nil
	}
}

func (s sessionDo) Take() (*model.Session, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Session), nil
	}
}

func (s sessionDo) Last() (*model.Session, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Session), nil
	}
}

func (s sessionDo) Find() ([]*model.Session, error) {
	result, err := s.DO.Find()
	return result.([]*model.Session), err
}

func (s sessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Session, err error) {
	buf := make([]*model.Session, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sessionDo) FindInBatches(result *[]*model.Session, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sessionDo) Attrs(attrs ...field.AssignExpr) ISessionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sessionDo) Assign(attrs ...field.AssignExpr) ISessionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sessionDo) Joins(fields ...field.RelationField) ISessionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sessionDo) Preload(fields ...field.RelationField) ISessionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sessionDo) FirstOrInit() (*model.Session, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Session), nil
	}
}

func (s sessionDo) FirstOrCreate() (*model.Session, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Session), nil
	}
}

func (s sessionDo) FindByPage(offset int, limit int) (result []*model.Session, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sessionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sessionDo) Delete(models ...*model.Session) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sessionDo) withDO(do gen.Dao) *sessionDo {
	s.DO = *do.(*gen.DO)
	return s
}
