// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tuihub/librarian/app/sephirah/internal/data/internal/ent/porterprivilege"
	"github.com/tuihub/librarian/app/sephirah/internal/data/internal/ent/predicate"
)

// PorterPrivilegeDelete is the builder for deleting a PorterPrivilege entity.
type PorterPrivilegeDelete struct {
	config
	hooks    []Hook
	mutation *PorterPrivilegeMutation
}

// Where appends a list predicates to the PorterPrivilegeDelete builder.
func (ppd *PorterPrivilegeDelete) Where(ps ...predicate.PorterPrivilege) *PorterPrivilegeDelete {
	ppd.mutation.Where(ps...)
	return ppd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ppd *PorterPrivilegeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ppd.sqlExec, ppd.mutation, ppd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ppd *PorterPrivilegeDelete) ExecX(ctx context.Context) int {
	n, err := ppd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ppd *PorterPrivilegeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(porterprivilege.Table, sqlgraph.NewFieldSpec(porterprivilege.FieldID, field.TypeInt))
	if ps := ppd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ppd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ppd.mutation.done = true
	return affected, err
}

// PorterPrivilegeDeleteOne is the builder for deleting a single PorterPrivilege entity.
type PorterPrivilegeDeleteOne struct {
	ppd *PorterPrivilegeDelete
}

// Where appends a list predicates to the PorterPrivilegeDelete builder.
func (ppdo *PorterPrivilegeDeleteOne) Where(ps ...predicate.PorterPrivilege) *PorterPrivilegeDeleteOne {
	ppdo.ppd.mutation.Where(ps...)
	return ppdo
}

// Exec executes the deletion query.
func (ppdo *PorterPrivilegeDeleteOne) Exec(ctx context.Context) error {
	n, err := ppdo.ppd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{porterprivilege.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ppdo *PorterPrivilegeDeleteOne) ExecX(ctx context.Context) {
	if err := ppdo.Exec(ctx); err != nil {
		panic(err)
	}
}
