// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/tuihub/librarian/internal/model"
	"github.com/tuihub/librarian/internal/model/modelnetzach"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newNotifyFlow(db *gorm.DB, opts ...gen.DOOption) notifyFlow {
	_notifyFlow := notifyFlow{}

	_notifyFlow.notifyFlowDo.UseDB(db, opts...)
	_notifyFlow.notifyFlowDo.UseModel(&modelnetzach.NotifyFlow{})

	tableName := _notifyFlow.notifyFlowDo.TableName()
	_notifyFlow.ALL = field.NewAsterisk(tableName)
	_notifyFlow.ID = field.NewInt64(tableName, "id")
	_notifyFlow.OwnerID = field.NewInt64(tableName, "user_notify_flow")
	_notifyFlow.Name = field.NewString(tableName, "name")
	_notifyFlow.Description = field.NewString(tableName, "description")
	_notifyFlow.Status = field.NewField(tableName, "status")
	_notifyFlow.UpdatedAt = field.NewTime(tableName, "updated_at")
	_notifyFlow.CreatedAt = field.NewTime(tableName, "created_at")
	_notifyFlow.Sources = notifyFlowHasManySources{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Sources", "modelnetzach.NotifyFlowSource"),
	}

	_notifyFlow.Targets = notifyFlowHasManyTargets{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Targets", "modelnetzach.NotifyFlowTarget"),
	}

	_notifyFlow.Owner = notifyFlowBelongsToOwner{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Owner", "model.User"),
		Sessions: struct {
			field.RelationField
			Device struct {
				field.RelationField
				Sessions struct {
					field.RelationField
				}
			}
			User struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Owner.Sessions", "model.Session"),
			Device: struct {
				field.RelationField
				Sessions struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Owner.Sessions.Device", "model.Device"),
				Sessions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Owner.Sessions.Device.Sessions", "model.Session"),
				},
			},
			User: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Owner.Sessions.User", "model.User"),
			},
		},
		Account: struct {
			field.RelationField
			BoundUser struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Owner.Account", "model.Account"),
			BoundUser: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Owner.Account.BoundUser", "model.User"),
			},
		},
	}

	_notifyFlow.fillFieldMap()

	return _notifyFlow
}

type notifyFlow struct {
	notifyFlowDo notifyFlowDo

	ALL         field.Asterisk
	ID          field.Int64
	OwnerID     field.Int64
	Name        field.String
	Description field.String
	Status      field.Field
	UpdatedAt   field.Time
	CreatedAt   field.Time
	Sources     notifyFlowHasManySources

	Targets notifyFlowHasManyTargets

	Owner notifyFlowBelongsToOwner

	fieldMap map[string]field.Expr
}

func (n notifyFlow) Table(newTableName string) *notifyFlow {
	n.notifyFlowDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n notifyFlow) As(alias string) *notifyFlow {
	n.notifyFlowDo.DO = *(n.notifyFlowDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *notifyFlow) updateTableName(table string) *notifyFlow {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.OwnerID = field.NewInt64(table, "user_notify_flow")
	n.Name = field.NewString(table, "name")
	n.Description = field.NewString(table, "description")
	n.Status = field.NewField(table, "status")
	n.UpdatedAt = field.NewTime(table, "updated_at")
	n.CreatedAt = field.NewTime(table, "created_at")

	n.fillFieldMap()

	return n
}

func (n *notifyFlow) WithContext(ctx context.Context) INotifyFlowDo {
	return n.notifyFlowDo.WithContext(ctx)
}

func (n notifyFlow) TableName() string { return n.notifyFlowDo.TableName() }

func (n notifyFlow) Alias() string { return n.notifyFlowDo.Alias() }

func (n notifyFlow) Columns(cols ...field.Expr) gen.Columns { return n.notifyFlowDo.Columns(cols...) }

func (n *notifyFlow) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *notifyFlow) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 10)
	n.fieldMap["id"] = n.ID
	n.fieldMap["user_notify_flow"] = n.OwnerID
	n.fieldMap["name"] = n.Name
	n.fieldMap["description"] = n.Description
	n.fieldMap["status"] = n.Status
	n.fieldMap["updated_at"] = n.UpdatedAt
	n.fieldMap["created_at"] = n.CreatedAt

}

func (n notifyFlow) clone(db *gorm.DB) notifyFlow {
	n.notifyFlowDo.ReplaceConnPool(db.Statement.ConnPool)
	n.Sources.db = db.Session(&gorm.Session{Initialized: true})
	n.Sources.db.Statement.ConnPool = db.Statement.ConnPool
	n.Targets.db = db.Session(&gorm.Session{Initialized: true})
	n.Targets.db.Statement.ConnPool = db.Statement.ConnPool
	n.Owner.db = db.Session(&gorm.Session{Initialized: true})
	n.Owner.db.Statement.ConnPool = db.Statement.ConnPool
	return n
}

func (n notifyFlow) replaceDB(db *gorm.DB) notifyFlow {
	n.notifyFlowDo.ReplaceDB(db)
	n.Sources.db = db.Session(&gorm.Session{})
	n.Targets.db = db.Session(&gorm.Session{})
	n.Owner.db = db.Session(&gorm.Session{})
	return n
}

type notifyFlowHasManySources struct {
	db *gorm.DB

	field.RelationField
}

func (a notifyFlowHasManySources) Where(conds ...field.Expr) *notifyFlowHasManySources {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a notifyFlowHasManySources) WithContext(ctx context.Context) *notifyFlowHasManySources {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a notifyFlowHasManySources) Session(session *gorm.Session) *notifyFlowHasManySources {
	a.db = a.db.Session(session)
	return &a
}

func (a notifyFlowHasManySources) Model(m *modelnetzach.NotifyFlow) *notifyFlowHasManySourcesTx {
	return &notifyFlowHasManySourcesTx{a.db.Model(m).Association(a.Name())}
}

func (a notifyFlowHasManySources) Unscoped() *notifyFlowHasManySources {
	a.db = a.db.Unscoped()
	return &a
}

type notifyFlowHasManySourcesTx struct{ tx *gorm.Association }

func (a notifyFlowHasManySourcesTx) Find() (result []*modelnetzach.NotifyFlowSource, err error) {
	return result, a.tx.Find(&result)
}

func (a notifyFlowHasManySourcesTx) Append(values ...*modelnetzach.NotifyFlowSource) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a notifyFlowHasManySourcesTx) Replace(values ...*modelnetzach.NotifyFlowSource) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a notifyFlowHasManySourcesTx) Delete(values ...*modelnetzach.NotifyFlowSource) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a notifyFlowHasManySourcesTx) Clear() error {
	return a.tx.Clear()
}

func (a notifyFlowHasManySourcesTx) Count() int64 {
	return a.tx.Count()
}

func (a notifyFlowHasManySourcesTx) Unscoped() *notifyFlowHasManySourcesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type notifyFlowHasManyTargets struct {
	db *gorm.DB

	field.RelationField
}

func (a notifyFlowHasManyTargets) Where(conds ...field.Expr) *notifyFlowHasManyTargets {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a notifyFlowHasManyTargets) WithContext(ctx context.Context) *notifyFlowHasManyTargets {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a notifyFlowHasManyTargets) Session(session *gorm.Session) *notifyFlowHasManyTargets {
	a.db = a.db.Session(session)
	return &a
}

func (a notifyFlowHasManyTargets) Model(m *modelnetzach.NotifyFlow) *notifyFlowHasManyTargetsTx {
	return &notifyFlowHasManyTargetsTx{a.db.Model(m).Association(a.Name())}
}

func (a notifyFlowHasManyTargets) Unscoped() *notifyFlowHasManyTargets {
	a.db = a.db.Unscoped()
	return &a
}

type notifyFlowHasManyTargetsTx struct{ tx *gorm.Association }

func (a notifyFlowHasManyTargetsTx) Find() (result []*modelnetzach.NotifyFlowTarget, err error) {
	return result, a.tx.Find(&result)
}

func (a notifyFlowHasManyTargetsTx) Append(values ...*modelnetzach.NotifyFlowTarget) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a notifyFlowHasManyTargetsTx) Replace(values ...*modelnetzach.NotifyFlowTarget) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a notifyFlowHasManyTargetsTx) Delete(values ...*modelnetzach.NotifyFlowTarget) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a notifyFlowHasManyTargetsTx) Clear() error {
	return a.tx.Clear()
}

func (a notifyFlowHasManyTargetsTx) Count() int64 {
	return a.tx.Count()
}

func (a notifyFlowHasManyTargetsTx) Unscoped() *notifyFlowHasManyTargetsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type notifyFlowBelongsToOwner struct {
	db *gorm.DB

	field.RelationField

	Sessions struct {
		field.RelationField
		Device struct {
			field.RelationField
			Sessions struct {
				field.RelationField
			}
		}
		User struct {
			field.RelationField
		}
	}
	Account struct {
		field.RelationField
		BoundUser struct {
			field.RelationField
		}
	}
}

func (a notifyFlowBelongsToOwner) Where(conds ...field.Expr) *notifyFlowBelongsToOwner {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a notifyFlowBelongsToOwner) WithContext(ctx context.Context) *notifyFlowBelongsToOwner {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a notifyFlowBelongsToOwner) Session(session *gorm.Session) *notifyFlowBelongsToOwner {
	a.db = a.db.Session(session)
	return &a
}

func (a notifyFlowBelongsToOwner) Model(m *modelnetzach.NotifyFlow) *notifyFlowBelongsToOwnerTx {
	return &notifyFlowBelongsToOwnerTx{a.db.Model(m).Association(a.Name())}
}

func (a notifyFlowBelongsToOwner) Unscoped() *notifyFlowBelongsToOwner {
	a.db = a.db.Unscoped()
	return &a
}

type notifyFlowBelongsToOwnerTx struct{ tx *gorm.Association }

func (a notifyFlowBelongsToOwnerTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a notifyFlowBelongsToOwnerTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a notifyFlowBelongsToOwnerTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a notifyFlowBelongsToOwnerTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a notifyFlowBelongsToOwnerTx) Clear() error {
	return a.tx.Clear()
}

func (a notifyFlowBelongsToOwnerTx) Count() int64 {
	return a.tx.Count()
}

func (a notifyFlowBelongsToOwnerTx) Unscoped() *notifyFlowBelongsToOwnerTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type notifyFlowDo struct{ gen.DO }

type INotifyFlowDo interface {
	gen.SubQuery
	Debug() INotifyFlowDo
	WithContext(ctx context.Context) INotifyFlowDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INotifyFlowDo
	WriteDB() INotifyFlowDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INotifyFlowDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INotifyFlowDo
	Not(conds ...gen.Condition) INotifyFlowDo
	Or(conds ...gen.Condition) INotifyFlowDo
	Select(conds ...field.Expr) INotifyFlowDo
	Where(conds ...gen.Condition) INotifyFlowDo
	Order(conds ...field.Expr) INotifyFlowDo
	Distinct(cols ...field.Expr) INotifyFlowDo
	Omit(cols ...field.Expr) INotifyFlowDo
	Join(table schema.Tabler, on ...field.Expr) INotifyFlowDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INotifyFlowDo
	RightJoin(table schema.Tabler, on ...field.Expr) INotifyFlowDo
	Group(cols ...field.Expr) INotifyFlowDo
	Having(conds ...gen.Condition) INotifyFlowDo
	Limit(limit int) INotifyFlowDo
	Offset(offset int) INotifyFlowDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INotifyFlowDo
	Unscoped() INotifyFlowDo
	Create(values ...*modelnetzach.NotifyFlow) error
	CreateInBatches(values []*modelnetzach.NotifyFlow, batchSize int) error
	Save(values ...*modelnetzach.NotifyFlow) error
	First() (*modelnetzach.NotifyFlow, error)
	Take() (*modelnetzach.NotifyFlow, error)
	Last() (*modelnetzach.NotifyFlow, error)
	Find() ([]*modelnetzach.NotifyFlow, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*modelnetzach.NotifyFlow, err error)
	FindInBatches(result *[]*modelnetzach.NotifyFlow, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*modelnetzach.NotifyFlow) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INotifyFlowDo
	Assign(attrs ...field.AssignExpr) INotifyFlowDo
	Joins(fields ...field.RelationField) INotifyFlowDo
	Preload(fields ...field.RelationField) INotifyFlowDo
	FirstOrInit() (*modelnetzach.NotifyFlow, error)
	FirstOrCreate() (*modelnetzach.NotifyFlow, error)
	FindByPage(offset int, limit int) (result []*modelnetzach.NotifyFlow, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INotifyFlowDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n notifyFlowDo) Debug() INotifyFlowDo {
	return n.withDO(n.DO.Debug())
}

func (n notifyFlowDo) WithContext(ctx context.Context) INotifyFlowDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n notifyFlowDo) ReadDB() INotifyFlowDo {
	return n.Clauses(dbresolver.Read)
}

func (n notifyFlowDo) WriteDB() INotifyFlowDo {
	return n.Clauses(dbresolver.Write)
}

func (n notifyFlowDo) Session(config *gorm.Session) INotifyFlowDo {
	return n.withDO(n.DO.Session(config))
}

func (n notifyFlowDo) Clauses(conds ...clause.Expression) INotifyFlowDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n notifyFlowDo) Returning(value interface{}, columns ...string) INotifyFlowDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n notifyFlowDo) Not(conds ...gen.Condition) INotifyFlowDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n notifyFlowDo) Or(conds ...gen.Condition) INotifyFlowDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n notifyFlowDo) Select(conds ...field.Expr) INotifyFlowDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n notifyFlowDo) Where(conds ...gen.Condition) INotifyFlowDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n notifyFlowDo) Order(conds ...field.Expr) INotifyFlowDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n notifyFlowDo) Distinct(cols ...field.Expr) INotifyFlowDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n notifyFlowDo) Omit(cols ...field.Expr) INotifyFlowDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n notifyFlowDo) Join(table schema.Tabler, on ...field.Expr) INotifyFlowDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n notifyFlowDo) LeftJoin(table schema.Tabler, on ...field.Expr) INotifyFlowDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n notifyFlowDo) RightJoin(table schema.Tabler, on ...field.Expr) INotifyFlowDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n notifyFlowDo) Group(cols ...field.Expr) INotifyFlowDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n notifyFlowDo) Having(conds ...gen.Condition) INotifyFlowDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n notifyFlowDo) Limit(limit int) INotifyFlowDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n notifyFlowDo) Offset(offset int) INotifyFlowDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n notifyFlowDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INotifyFlowDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n notifyFlowDo) Unscoped() INotifyFlowDo {
	return n.withDO(n.DO.Unscoped())
}

func (n notifyFlowDo) Create(values ...*modelnetzach.NotifyFlow) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n notifyFlowDo) CreateInBatches(values []*modelnetzach.NotifyFlow, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n notifyFlowDo) Save(values ...*modelnetzach.NotifyFlow) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n notifyFlowDo) First() (*modelnetzach.NotifyFlow, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*modelnetzach.NotifyFlow), nil
	}
}

func (n notifyFlowDo) Take() (*modelnetzach.NotifyFlow, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*modelnetzach.NotifyFlow), nil
	}
}

func (n notifyFlowDo) Last() (*modelnetzach.NotifyFlow, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*modelnetzach.NotifyFlow), nil
	}
}

func (n notifyFlowDo) Find() ([]*modelnetzach.NotifyFlow, error) {
	result, err := n.DO.Find()
	return result.([]*modelnetzach.NotifyFlow), err
}

func (n notifyFlowDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*modelnetzach.NotifyFlow, err error) {
	buf := make([]*modelnetzach.NotifyFlow, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n notifyFlowDo) FindInBatches(result *[]*modelnetzach.NotifyFlow, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n notifyFlowDo) Attrs(attrs ...field.AssignExpr) INotifyFlowDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n notifyFlowDo) Assign(attrs ...field.AssignExpr) INotifyFlowDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n notifyFlowDo) Joins(fields ...field.RelationField) INotifyFlowDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n notifyFlowDo) Preload(fields ...field.RelationField) INotifyFlowDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n notifyFlowDo) FirstOrInit() (*modelnetzach.NotifyFlow, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*modelnetzach.NotifyFlow), nil
	}
}

func (n notifyFlowDo) FirstOrCreate() (*modelnetzach.NotifyFlow, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*modelnetzach.NotifyFlow), nil
	}
}

func (n notifyFlowDo) FindByPage(offset int, limit int) (result []*modelnetzach.NotifyFlow, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n notifyFlowDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n notifyFlowDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n notifyFlowDo) Delete(models ...*modelnetzach.NotifyFlow) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *notifyFlowDo) withDO(do gen.Dao) *notifyFlowDo {
	n.DO = *do.(*gen.DO)
	return n
}
