// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/tuihub/librarian/internal/model/modelgebura"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSentinelLibrary(db *gorm.DB, opts ...gen.DOOption) sentinelLibrary {
	_sentinelLibrary := sentinelLibrary{}

	_sentinelLibrary.sentinelLibraryDo.UseDB(db, opts...)
	_sentinelLibrary.sentinelLibraryDo.UseModel(&modelgebura.SentinelLibrary{})

	tableName := _sentinelLibrary.sentinelLibraryDo.TableName()
	_sentinelLibrary.ALL = field.NewAsterisk(tableName)
	_sentinelLibrary.ID = field.NewInt64(tableName, "id")
	_sentinelLibrary.SentinelID = field.NewInt64(tableName, "sentinel_id")
	_sentinelLibrary.ReportedID = field.NewInt64(tableName, "reported_id")
	_sentinelLibrary.DownloadBasePath = field.NewString(tableName, "download_base_path")
	_sentinelLibrary.CreatedAt = field.NewTime(tableName, "created_at")
	_sentinelLibrary.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sentinelLibrary.AppBinaries = sentinelLibraryHasManyAppBinaries{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AppBinaries", "modelgebura.SentinelAppBinary"),
		Files: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("AppBinaries.Files", "modelgebura.SentinelAppBinaryFile"),
		},
	}

	_sentinelLibrary.fillFieldMap()

	return _sentinelLibrary
}

type sentinelLibrary struct {
	sentinelLibraryDo sentinelLibraryDo

	ALL              field.Asterisk
	ID               field.Int64
	SentinelID       field.Int64
	ReportedID       field.Int64
	DownloadBasePath field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	AppBinaries      sentinelLibraryHasManyAppBinaries

	fieldMap map[string]field.Expr
}

func (s sentinelLibrary) Table(newTableName string) *sentinelLibrary {
	s.sentinelLibraryDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sentinelLibrary) As(alias string) *sentinelLibrary {
	s.sentinelLibraryDo.DO = *(s.sentinelLibraryDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sentinelLibrary) updateTableName(table string) *sentinelLibrary {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.SentinelID = field.NewInt64(table, "sentinel_id")
	s.ReportedID = field.NewInt64(table, "reported_id")
	s.DownloadBasePath = field.NewString(table, "download_base_path")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *sentinelLibrary) WithContext(ctx context.Context) ISentinelLibraryDo {
	return s.sentinelLibraryDo.WithContext(ctx)
}

func (s sentinelLibrary) TableName() string { return s.sentinelLibraryDo.TableName() }

func (s sentinelLibrary) Alias() string { return s.sentinelLibraryDo.Alias() }

func (s sentinelLibrary) Columns(cols ...field.Expr) gen.Columns {
	return s.sentinelLibraryDo.Columns(cols...)
}

func (s *sentinelLibrary) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sentinelLibrary) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["sentinel_id"] = s.SentinelID
	s.fieldMap["reported_id"] = s.ReportedID
	s.fieldMap["download_base_path"] = s.DownloadBasePath
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt

}

func (s sentinelLibrary) clone(db *gorm.DB) sentinelLibrary {
	s.sentinelLibraryDo.ReplaceConnPool(db.Statement.ConnPool)
	s.AppBinaries.db = db.Session(&gorm.Session{Initialized: true})
	s.AppBinaries.db.Statement.ConnPool = db.Statement.ConnPool
	return s
}

func (s sentinelLibrary) replaceDB(db *gorm.DB) sentinelLibrary {
	s.sentinelLibraryDo.ReplaceDB(db)
	s.AppBinaries.db = db.Session(&gorm.Session{})
	return s
}

type sentinelLibraryHasManyAppBinaries struct {
	db *gorm.DB

	field.RelationField

	Files struct {
		field.RelationField
	}
}

func (a sentinelLibraryHasManyAppBinaries) Where(conds ...field.Expr) *sentinelLibraryHasManyAppBinaries {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a sentinelLibraryHasManyAppBinaries) WithContext(ctx context.Context) *sentinelLibraryHasManyAppBinaries {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a sentinelLibraryHasManyAppBinaries) Session(session *gorm.Session) *sentinelLibraryHasManyAppBinaries {
	a.db = a.db.Session(session)
	return &a
}

func (a sentinelLibraryHasManyAppBinaries) Model(m *modelgebura.SentinelLibrary) *sentinelLibraryHasManyAppBinariesTx {
	return &sentinelLibraryHasManyAppBinariesTx{a.db.Model(m).Association(a.Name())}
}

func (a sentinelLibraryHasManyAppBinaries) Unscoped() *sentinelLibraryHasManyAppBinaries {
	a.db = a.db.Unscoped()
	return &a
}

type sentinelLibraryHasManyAppBinariesTx struct{ tx *gorm.Association }

func (a sentinelLibraryHasManyAppBinariesTx) Find() (result []*modelgebura.SentinelAppBinary, err error) {
	return result, a.tx.Find(&result)
}

func (a sentinelLibraryHasManyAppBinariesTx) Append(values ...*modelgebura.SentinelAppBinary) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a sentinelLibraryHasManyAppBinariesTx) Replace(values ...*modelgebura.SentinelAppBinary) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a sentinelLibraryHasManyAppBinariesTx) Delete(values ...*modelgebura.SentinelAppBinary) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a sentinelLibraryHasManyAppBinariesTx) Clear() error {
	return a.tx.Clear()
}

func (a sentinelLibraryHasManyAppBinariesTx) Count() int64 {
	return a.tx.Count()
}

func (a sentinelLibraryHasManyAppBinariesTx) Unscoped() *sentinelLibraryHasManyAppBinariesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type sentinelLibraryDo struct{ gen.DO }

type ISentinelLibraryDo interface {
	gen.SubQuery
	Debug() ISentinelLibraryDo
	WithContext(ctx context.Context) ISentinelLibraryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISentinelLibraryDo
	WriteDB() ISentinelLibraryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISentinelLibraryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISentinelLibraryDo
	Not(conds ...gen.Condition) ISentinelLibraryDo
	Or(conds ...gen.Condition) ISentinelLibraryDo
	Select(conds ...field.Expr) ISentinelLibraryDo
	Where(conds ...gen.Condition) ISentinelLibraryDo
	Order(conds ...field.Expr) ISentinelLibraryDo
	Distinct(cols ...field.Expr) ISentinelLibraryDo
	Omit(cols ...field.Expr) ISentinelLibraryDo
	Join(table schema.Tabler, on ...field.Expr) ISentinelLibraryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISentinelLibraryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISentinelLibraryDo
	Group(cols ...field.Expr) ISentinelLibraryDo
	Having(conds ...gen.Condition) ISentinelLibraryDo
	Limit(limit int) ISentinelLibraryDo
	Offset(offset int) ISentinelLibraryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISentinelLibraryDo
	Unscoped() ISentinelLibraryDo
	Create(values ...*modelgebura.SentinelLibrary) error
	CreateInBatches(values []*modelgebura.SentinelLibrary, batchSize int) error
	Save(values ...*modelgebura.SentinelLibrary) error
	First() (*modelgebura.SentinelLibrary, error)
	Take() (*modelgebura.SentinelLibrary, error)
	Last() (*modelgebura.SentinelLibrary, error)
	Find() ([]*modelgebura.SentinelLibrary, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*modelgebura.SentinelLibrary, err error)
	FindInBatches(result *[]*modelgebura.SentinelLibrary, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*modelgebura.SentinelLibrary) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISentinelLibraryDo
	Assign(attrs ...field.AssignExpr) ISentinelLibraryDo
	Joins(fields ...field.RelationField) ISentinelLibraryDo
	Preload(fields ...field.RelationField) ISentinelLibraryDo
	FirstOrInit() (*modelgebura.SentinelLibrary, error)
	FirstOrCreate() (*modelgebura.SentinelLibrary, error)
	FindByPage(offset int, limit int) (result []*modelgebura.SentinelLibrary, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISentinelLibraryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sentinelLibraryDo) Debug() ISentinelLibraryDo {
	return s.withDO(s.DO.Debug())
}

func (s sentinelLibraryDo) WithContext(ctx context.Context) ISentinelLibraryDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sentinelLibraryDo) ReadDB() ISentinelLibraryDo {
	return s.Clauses(dbresolver.Read)
}

func (s sentinelLibraryDo) WriteDB() ISentinelLibraryDo {
	return s.Clauses(dbresolver.Write)
}

func (s sentinelLibraryDo) Session(config *gorm.Session) ISentinelLibraryDo {
	return s.withDO(s.DO.Session(config))
}

func (s sentinelLibraryDo) Clauses(conds ...clause.Expression) ISentinelLibraryDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sentinelLibraryDo) Returning(value interface{}, columns ...string) ISentinelLibraryDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sentinelLibraryDo) Not(conds ...gen.Condition) ISentinelLibraryDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sentinelLibraryDo) Or(conds ...gen.Condition) ISentinelLibraryDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sentinelLibraryDo) Select(conds ...field.Expr) ISentinelLibraryDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sentinelLibraryDo) Where(conds ...gen.Condition) ISentinelLibraryDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sentinelLibraryDo) Order(conds ...field.Expr) ISentinelLibraryDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sentinelLibraryDo) Distinct(cols ...field.Expr) ISentinelLibraryDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sentinelLibraryDo) Omit(cols ...field.Expr) ISentinelLibraryDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sentinelLibraryDo) Join(table schema.Tabler, on ...field.Expr) ISentinelLibraryDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sentinelLibraryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISentinelLibraryDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sentinelLibraryDo) RightJoin(table schema.Tabler, on ...field.Expr) ISentinelLibraryDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sentinelLibraryDo) Group(cols ...field.Expr) ISentinelLibraryDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sentinelLibraryDo) Having(conds ...gen.Condition) ISentinelLibraryDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sentinelLibraryDo) Limit(limit int) ISentinelLibraryDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sentinelLibraryDo) Offset(offset int) ISentinelLibraryDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sentinelLibraryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISentinelLibraryDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sentinelLibraryDo) Unscoped() ISentinelLibraryDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sentinelLibraryDo) Create(values ...*modelgebura.SentinelLibrary) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sentinelLibraryDo) CreateInBatches(values []*modelgebura.SentinelLibrary, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sentinelLibraryDo) Save(values ...*modelgebura.SentinelLibrary) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sentinelLibraryDo) First() (*modelgebura.SentinelLibrary, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*modelgebura.SentinelLibrary), nil
	}
}

func (s sentinelLibraryDo) Take() (*modelgebura.SentinelLibrary, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*modelgebura.SentinelLibrary), nil
	}
}

func (s sentinelLibraryDo) Last() (*modelgebura.SentinelLibrary, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*modelgebura.SentinelLibrary), nil
	}
}

func (s sentinelLibraryDo) Find() ([]*modelgebura.SentinelLibrary, error) {
	result, err := s.DO.Find()
	return result.([]*modelgebura.SentinelLibrary), err
}

func (s sentinelLibraryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*modelgebura.SentinelLibrary, err error) {
	buf := make([]*modelgebura.SentinelLibrary, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sentinelLibraryDo) FindInBatches(result *[]*modelgebura.SentinelLibrary, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sentinelLibraryDo) Attrs(attrs ...field.AssignExpr) ISentinelLibraryDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sentinelLibraryDo) Assign(attrs ...field.AssignExpr) ISentinelLibraryDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sentinelLibraryDo) Joins(fields ...field.RelationField) ISentinelLibraryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sentinelLibraryDo) Preload(fields ...field.RelationField) ISentinelLibraryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sentinelLibraryDo) FirstOrInit() (*modelgebura.SentinelLibrary, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*modelgebura.SentinelLibrary), nil
	}
}

func (s sentinelLibraryDo) FirstOrCreate() (*modelgebura.SentinelLibrary, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*modelgebura.SentinelLibrary), nil
	}
}

func (s sentinelLibraryDo) FindByPage(offset int, limit int) (result []*modelgebura.SentinelLibrary, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sentinelLibraryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sentinelLibraryDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sentinelLibraryDo) Delete(models ...*modelgebura.SentinelLibrary) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sentinelLibraryDo) withDO(do gen.Dao) *sentinelLibraryDo {
	s.DO = *do.(*gen.DO)
	return s
}
