[server.grpc]
addr = "0.0.0.0:10000"
timeout = "1s"

[server.grpc_web]
addr = "0.0.0.0:10001"
timeout = "1s"

[database]
driver = "postgres"
host = "localhost"
port = 5432
dbname = "librarian"
user = "librarian"
password = "librarian"
no_ssl = true

[s3]
end_point = "127.0.0.1:9000"
access_key = "librarian"
secret_key = "librarian"
use_ssl = false

[auth]
password_salt = "test"
jwt_issuer = "test"
jwt_secret = "test"

[mq]
driver = "redis"

[cache]
driver = "redis"
addr = "localhost:6379"

[searcher.data.meilisearch]
addr = "http://localhost:7700"

[miner.data]
